### ISSUE TITLE
Quotes in attribute selectors are not being handled 

### ISSUE THREAD

**Issue by chelseario** [abw/HTML-Query#6]
I'm having a problem with attribute selectors within my application. While investigating I noticed that there are no tests that exercise single-quoted and double-quoted attribute values, instead only the unquoted variant is exercised.

Attribute selectors are fairly common in CSS and while they don't always have quotes, they should be handled appropriately if they do, which can only be confirmed functional if the tests try all the permutations.

**Comment by kamelkev** [comment]
Yeah I see what you mean. I updated the acidtest.t to try the different types of quoting.

You can see here:
https://github.com/abw/HTML-Query/commit/be548c0996ea7f552c23b91afef417d5ac00b493

Everything here looks fine, no functionality changes necessary, so new version will be generated.
